# african cities - ONLY IN ORACLE
SELECT CTY.NAME
  FROM CITY CTY, COUNTRY CNY
  WHERE CTY.COUNTRYCODE = CNY.CODE
  AND CNY.CONTINENT = 'Africa';

#  Asian Population - ONLY IN ORACLE
SELECT SUM(CTY.POPULATION)
  FROM CITY CTY, COUNTRY CNY
  WHERE CTY.COUNTRYCODE = CNY.CODE
  AND CNY.CONTINENT = 'Asia';

# AVERAGE POPULATION OF CITIES ON CONTINENTS - ONLY IN ORACLE
SELECT CNY.CONTINENT, TRUNC(AVG(CTY.POPULATION),0)
  FROM CITY CTY, COUNTRY CNY
  WHERE CTY.COUNTRYCODE = CNY.CODE
  GROUP BY CNY.CONTINENT;
