
# FOR SELECT ALL challenge
SELECT * FROM CITY;

# FOR SELECT by Id

SELECT * FROM CITY WHERE ID = 1661;

# FOR JAPANESE CITIES DETAIL

SELECT * FROM CITY WHERE CountryCode = 'JPN';

# JAPANESE CITY NAMES

SELECT Name FROM CITY WHERE CountryCode = 'JPN';

# Weather Observation Station 1

SELECT CITY, STATE FROM STATION

# Weather Observation Station 3

SELECT DISTINCT CITY FROM STATION WHERE ID % 2 = 0 ORDER BY CITY;

# Weather Observation Station 4

SELECT (COUNT(CITY) - COUNT(DISTINCT CITY)) FROM STATION;

# Weather Observation Station 5

SELECT TOP 1 CITY, LEN(CITY) FROM STATION ORDER BY LEN(CITY), CITY;
SELECT TOP 1 CITY, LEN(CITY) FROM STATION ORDER BY LEN(CITY) DESC, CITY DESC;


# Weather Observation Station 6
SELECT DISTINCT CITY FROM STATION
WHERE
CITY LIKE 'a%' OR
CITY LIKE 'e%' OR
CITY LIKE 'i%' OR
CITY LIKE 'o%' OR
CITY LIKE 'u%'
ORDER BY CITY;

# Weather Observation Station 7
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE '%[aeiouAEIOU]'
ORDER BY CITY;

# Weather Observation Station 8

SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE '[aeiouAEIOU]%[aeiouAEIOU]'
ORDER BY CITY;

# Weather Observation Station 9

SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE '[aeiouAEIOU]%'
ORDER BY CITY;

# Weather Observation Station 10
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE '%[aeiouAEIOU]'
ORDER BY CITY;

# Weather Observation Station 11
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE '[aeiouAEIOU]%[aeiouAEIOU]'
ORDER BY CITY;

# Weather Observation Station 12
SELECT DISTINCT CITY FROM STATION
WHERE
CITY NOT LIKE '[aeiouAEIOU]%' AND
CITY NOT LIKE '%[aeiouAEIOU]'
ORDER BY CITY;
